---
#Update system
- name: Update all packages to the latest version
  apt:
    upgrade: dist
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes 
- name: Remove useless packages from the cache
  apt:
    autoclean: yes
